/**
 * React → static SVG → HyperFrames block.
 *
 * WHY THIS EXISTS
 * HyperFrames seeks frames non-linearly and needs every frame reproducible from its
 * time value alone. React's runtime (state, effects, rAF-driven animation libraries)
 * is the opposite of that contract, so React must not ship to the renderer.
 *
 * But React's *layout* work — scales, curve interpolation, axis ticks, stacking — is
 * pure computation that can happen once, at build time. So we run visx here in Node,
 * serialise the result to static SVG, measure the path in Node too, and emit a block
 * whose only runtime dependency is GSAP tweening a baked dash offset.
 *
 * Run:  npm run build
 */
import { createElement as h } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { LinePath, AreaClosed } from "@visx/shape";
import { scaleLinear } from "@visx/scale";
import { curveMonotoneX } from "@visx/curve";
import { svgPathProperties } from "svg-path-properties";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dir, "../../blocks/ugc-react-chart/ugc-react-chart.html");

/* ------------------------------------------------------------------ config */
const CFG = {
  title: "Revenue",
  headline: 46250,
  caption: "and a clean summary",
  accent: "#7C5CE6",
  series: [12, 19, 17, 28, 26, 41, 52, 49, 68, 74, 91, 104],
  width: 880,
  height: 420,
  pad: { top: 24, right: 24, bottom: 24, left: 24 },
};

/* ------------------------------------------------- React does the geometry */
const innerW = CFG.width - CFG.pad.left - CFG.pad.right;
const innerH = CFG.height - CFG.pad.top - CFG.pad.bottom;

const x = scaleLinear({ domain: [0, CFG.series.length - 1], range: [0, innerW] });
const y = scaleLinear({ domain: [0, Math.max(...CFG.series) * 1.1], range: [innerH, 0] });

const data = CFG.series.map((v, i) => ({ i, v }));
const getX = (d) => x(d.i);
const getY = (d) => y(d.v);

// renderToStaticMarkup gives us plain SVG with no React attributes and no runtime.
const chartSvg = renderToStaticMarkup(
  h(
    "svg",
    {
      viewBox: `0 0 ${CFG.width} ${CFG.height}`,
      width: CFG.width,
      height: CFG.height,
      fill: "none",
      xmlns: "http://www.w3.org/2000/svg",
    },
    h(
      "g",
      { transform: `translate(${CFG.pad.left},${CFG.pad.top})` },
      h(AreaClosed, {
        id: "uk-area",
        data,
        x: getX,
        y: getY,
        yScale: y,
        curve: curveMonotoneX,
        fill: CFG.accent,
        fillOpacity: 0.14,
      }),
      h(LinePath, {
        id: "uk-line",
        data,
        x: getX,
        y: getY,
        curve: curveMonotoneX,
        stroke: CFG.accent,
        strokeWidth: 6,
        strokeLinecap: "round",
        strokeLinejoin: "round",
      }),
    ),
  ),
);

/* ------------------------------- measure in Node, so the renderer never has to */
// getTotalLength() only exists in a browser, and calling it from a timeline callback
// is seek-order dependent. Measuring here bakes it into a constant instead.
// visx emits attributes in its own order (d before id), so find the element first,
// then pull d out of it — never assume attribute order in generated markup.
const lineTag = /<path[^>]*\bid="uk-line"[^>]*>/.exec(chartSvg)?.[0] ?? "";
const lineD = /\bd="([^"]+)"/.exec(lineTag)?.[1] ?? "";
if (!lineD) throw new Error("could not extract the line path from the rendered SVG");
const pathLen = Math.ceil(new svgPathProperties(lineD).getTotalLength());

// Scale output carries ~15 significant digits; round to 2dp to keep the block readable.
const round2 = (svg) =>
  svg.replace(/\bd="([^"]+)"/g, (m, d) => `d="${d.replace(/-?\d+\.\d+/g, (n) => (+n).toFixed(2))}"`);
const chartSvgOut = round2(chartSvg);

/* ------------------------------------------------------------ emit the block */
const page = `<!-- hyperframes-registry-item: ugc-react-chart -->
<!-- GENERATED by registry/tools/react-prerender/build-chart.mjs — do not hand-edit. -->
<!-- React/visx computed this geometry at BUILD time; no React ships to the renderer. -->
<!doctype html>
<html
  lang="en"
  data-composition-variables='[
    {"id":"title","type":"string","label":"Panel title","default":"${CFG.title}"},
    {"id":"headline","type":"number","label":"Headline value","default":${CFG.headline}},
    {"id":"caption","type":"string","label":"Caption","default":"${CFG.caption}"}
  ]'
>
  <head>
    <meta charset="UTF-8" />
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      html, body { background: #FDFDFD; overflow: hidden; }
      body { width: 1080px; height: 1920px; }
      #root { position: absolute; inset: 0; }
      .fill { position: absolute; inset: 0; background: #FDFDFD; }
      .panel {
        position: absolute; left: 60px; top: 452px; width: 960px; height: 620px;
        background: #fff; border: 1.5px solid #ECEAE6; border-radius: 34px;
        box-shadow: 0 16px 40px rgba(17,17,17,.09); padding: 40px; opacity: 0;
      }
      .head { display: flex; align-items: center; gap: 16px; }
      .head .sq { display: block; width: 38px; height: 38px; border-radius: 11px; background: ${CFG.accent}; }
      .head .t { display: block; font-family: "Inter", sans-serif; font-weight: 700; font-size: 32px; color: #111; }
      .big {
        display: block; font-family: "Inter", sans-serif; font-weight: 900; font-size: 78px;
        line-height: 1; color: #111; margin-top: 22px; font-variant-numeric: tabular-nums;
      }
      .sub { display: block; font-family: "Inter", sans-serif; font-weight: 700; font-size: 24px; color: #12A150; margin-top: 10px; }
      .plot { position: absolute; left: 40px; right: 40px; bottom: 32px; height: 420px; }
      .plot svg { display: block; width: 100%; height: 420px; }
      .bcap {
        position: absolute; left: 0; top: 1180px; width: 1080px; text-align: center;
        font-family: "Playfair Display", serif; font-weight: 900; font-style: italic;
        font-size: 78px; text-transform: uppercase; color: #111;
        -webkit-text-stroke: 11px #FDFDFD; paint-order: stroke fill; opacity: 0;
      }
    </style>
  </head>
  <body>
    <div
      id="root"
      data-composition-id="ugc-react-chart"
      data-start="0"
      data-duration="5"
      data-width="1080"
      data-height="1920"
    >
      <div class="fill"></div>
      <div id="uk-panel" class="panel">
        <div class="head"><span class="sq"></span><span id="uk-title" class="t">${CFG.title}</span></div>
        <span id="uk-value" class="big">$0</span>
        <span class="sub">rendered by visx at build time</span>
        <div class="plot">${chartSvgOut}</div>
      </div>
      <div id="uk-cap" class="bcap">${CFG.caption}</div>
    </div>

    <script>
      (() => {
        // Baked at build time by svg-path-properties in Node — never measured here.
        const PATH_LEN = ${pathLen};

        const scene = document.querySelector('[data-composition-id="ugc-react-chart"]');
        const V =
          (window.__hyperframes && window.__hyperframes.getVariables
            ? window.__hyperframes.getVariables()
            : null) || {};
        const headline = isFinite(+V.headline) ? +V.headline : ${CFG.headline};
        scene.querySelector("#uk-title").textContent = V.title || ${JSON.stringify(CFG.title)};
        scene.querySelector("#uk-cap").textContent = V.caption || ${JSON.stringify(CFG.caption)};

        const line = scene.querySelector("#uk-line");
        const area = scene.querySelector("#uk-area");
        const valueEl = scene.querySelector("#uk-value");
        line.setAttribute("stroke-dasharray", PATH_LEN);
        valueEl.textContent = "$0";

        window.__timelines = window.__timelines || {};
        const tl = gsap.timeline({ paused: true });

        tl.set("#uk-panel", { opacity: 1 }, 0);
        tl.fromTo("#uk-panel", { scale: 0.82, y: 40 }, { scale: 1, y: 0, duration: 0.62, ease: "back.out(1.9)" }, 0);

        // svg-path-draw over the visx-generated curve.
        tl.fromTo(line, { strokeDashoffset: PATH_LEN }, { strokeDashoffset: 0, duration: 1.5, ease: "power2.out" }, 0.4);
        tl.fromTo(area, { opacity: 0 }, { opacity: 1, duration: 0.7, ease: "power2.out" }, 0.9);

        const m = { v: 0 };
        tl.to(m, {
          v: headline,
          duration: 1.5,
          ease: "power2.out",
          onUpdate: () => {
            valueEl.textContent = "$" + Math.round(m.v).toLocaleString("en-US");
          },
        }, 0.5);

        tl.set("#uk-cap", { opacity: 1 }, 2.3);
        tl.fromTo("#uk-cap", { y: 18, scale: 0.96 }, { y: 0, scale: 1, duration: 0.3, ease: "power3.out" }, 2.3);

        window.__timelines["ugc-react-chart"] = tl;
      })();
    </script>
  </body>
</html>
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, page);
console.log(`✓ ugc-react-chart.html written`);
console.log(`  series points : ${CFG.series.length}`);
console.log(`  svg bytes     : ${chartSvgOut.length}`);
console.log(`  baked path len: ${pathLen}`);
